### ISSUE TITLE
EntityManager closing semi-silently

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Mapping#10]
Merged fix-detach-error into csv-import.

With no csvimport-mappings to the Mapping plugin, import completes with nothing in jobs log, but doesn't get to recording the import data. Running from command line gives the message below

With mappings, same error in job log as #6 .

```
Fatal error: Uncaught exception 'Doctrine\ORM\ORMException' with message 'The EntityManager is closed.' in /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:144
Stack trace:
#0 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(741): Doctrine\ORM\ORMException::entityManagerClosed()
#1 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(354): Doctrine\ORM\EntityManager->errorIfClosed()
#2 /var/www/omekas/data/scripts/perform-job.php(46): Doctrine\ORM\EntityManager->flush()
#3 {main}
  thrown in /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php on line 144

Fatal error: Uncaught exception 'Doctrine\ORM\ORMException' with message 'The EntityManager is closed.' in /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php:144
Stack trace:
#0 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(741): Doctrine\ORM\ORMException::entityManagerClosed()
#1 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(665): Doctrine\ORM\EntityManager->errorIfClosed()
#2 /var/www/omekas/application/src/Job/Strategy/SynchronousStrategy.php(67): Doctrine\ORM\EntityManager->merge(Object(Omeka\Entity\Job))
#3 [internal function]: Omeka\Job\Strategy\SynchronousStrategy->handleFatalError(Object(Omeka\Entity\Job), Object(Doctrine\ORM\EntityManager))
#4 {main}
  thrown in /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php on line 144


```

**Comment by zerocrates** [comment]
Are there markers in this set? Different results if no markers mapped? That
could just be a matter of needing detach cascade from the mapping to the
markers.

Also, are you on the latest pull for core? That's where the fix for logging
lives.

**Comment by zerocrates** [comment]
Also some of those "entity manager is closed" errors are currently expected
whenever there's an error like this, just from other later flushes.

**Comment by zerocrates** [comment]
Posting the actual logged error is the easiest way to tell what's up, but my best guess is that it's just basically the same problem but this time with the MappingMarker entity. The message should look the same but with the name of the entity changed.

I'd thought the Markers were attached to the Mapping, so I could just rely on the detach cascading from one to the the other, but it seems they're instead directly related to the Item as well. If indeed that's what's happening (that MappingMarker is the entity mentioned in the error message), then the solution should be easy: just extend the "detacher" to also detach markers.
