### ISSUE TITLE
Mapping requiert Omeka S ^4.0.0

### ISSUE THREAD

**Issue by Dominique56** [omeka-s-modules/Mapping#100]
Version 1.6 requires Omeka 4.0 ????
Please correct
Sincerely

**Comment by jimsafley** [comment]
Version 1.6.0, [released on August 29](https://omeka.org/s/modules/Mapping/), requires Omeka S ^3.1.0. Are you perhaps trying to install directly from the `master` branch of this repository?

**Comment by Dominique56** [comment]
Thanks it' work
