### ISSUE TITLE
Readme correction about dependencies

### ISSUE THREAD

**Issue by pprw** [omeka-s-modules/Mapping#101]
With master versions of Omeka S and this module, the step `$ npm install` is not only needed to develop but also just to display the map.

Readme should be updated

> To develop on this repository, you must first install dependencies. Run $ npm install in the the module's /asset directory.

**Comment by jimsafley** [comment]
Does the README not already say exactly that? What would you add?

We haven't decided whether to a) push dependencies into this repo or b) require `npm install` for development, and package the dependencies for releases only. I suppose we're leaning on a) for the convenience of people who develop and test off of the master branch, but without tooling to cull unneeded files, the dependency size could grow pretty quickly.

**Comment by pprw** [comment]
> Does the README not already say exactly that? What would you add?

Readme says we need `npm install` "to develop". In fact, we need this step even when simply using the module (without, there is no map displayed). I think more and more users (not developers) install through cloning git repo because it easier to upgrade this way and they could think it is not mandatory for them to launch `npm install` with the current Readme.

**Comment by jimsafley** [comment]
I've pushed the dependencies (34ca441ecf3ea704082bd54a24441795a1025d06) and corrected the [README](https://github.com/omeka-s-modules/Mapping/blob/master/README.md).
