### ISSUE TITLE
Testing: Item advanced search, geographic location 

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#103]
The [geographic-location-advanced-search](https://github.com/omeka-s-modules/Mapping/compare/geographic-location-advanced-search) branch adds geographic location query to item advanced search. This feature already exists in Mapping's "Map browse" custom link, in site navigation. They both search within a radius of an address, but the existing feature searches for _markers_, while this new feature searches for _items_.

To test this you'll need a handful of items that have markers. Go to the item advanced search page and you should see a new "Geographic location" fieldset. Enter an address, a radius, and a radius unit, and submit the form. The result should only include items that have at least one marker within the set radius of the address. Try many combinations of addresses, radii, and radius units.

You'll also need to re-test the "Map browse" custom link on the public side because my changes affect that code, but they shouldn't affect the behavior.

**Comment by katknow** [comment]
This is working really well for me, but the new fields are only appearing for me on the advanced search on the back end. I tried in multiple browsers and it's the same. However, it does work really well on the back end and it does not appear to have affected the "Map browse."

**Comment by katknow** [comment]
....although this appears to be answered by the next issue in my queue!
