### ISSUE TITLE
Testing: Toggle to add Mapping fields to public advanced search; Mapping search filters

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#104]
Also included in the [geographic-location-advanced-search](https://github.com/omeka-s-modules/Mapping/tree/geographic-location-advanced-search) branch are a few new features that need to be tested. There are two new site settings: "Add marker presence to advanced search" and "Add geographic location to advanced search". They should be unchecked by default. By using these, site administrators can declare whether they want to include these fields in the public item advanced search. Try it out and see if it works as expected.

Also, the branch adds Mapping search filters above browse results after doing an advanced search. Test this out by using the Mapping fields in advanced search. On the resulting page, you should see "Map marker presence" and "Geographic location" above the results.

**Comment by katknow** [comment]
The "Map marker presence" search field is working perfectly. However, the "Geographic location" search is not working. I'm putting the exact same info in as the previous issue (#103) and getting no search results.

**Comment by jimsafley** [comment]
I made some changes that should fix the search. Test the admin item search, the public item search, and the public "Map browse" page.

**Comment by katknow** [comment]
The "Geographic location" search does work on each of these pages. Before I could fill in the address field without the radius and still pull up a marker based on the address alone. Now, I have to input the address and the radius (which I think is correct based on the wording in #103), but I wanted to mention it since it is different behavior.

**Comment by jimsafley** [comment]
It surprises me that the module allowed an address without a radius. That would just pull up every marker, which is the same as not putting in an address. Anyway, glad you brought it up. Strange, though.
