### ISSUE TITLE
Documentation: Geographic location for item advanced search

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#105]
See #103 and #104 for changes that need documentation.

**Comment by allanaaa** [comment]
Is this the only use of a fieldset legend on the advanced search form? It looks a bit out of place.
![fieldset2](https://user-images.githubusercontent.com/28012148/211053916-20f1a9f4-e1a6-4b27-93f6-a64c27dc928a.PNG)
![fieldsetdefault](https://user-images.githubusercontent.com/28012148/211053922-37b674a2-a079-4699-958a-6fd4a82618b3.PNG)
![fieldset1](https://user-images.githubusercontent.com/28012148/211053925-44625981-3e67-4d69-af9d-1f9eb8312626.PNG)

**Comment by allanaaa** [comment]
Leaving this one open as the fieldset thing might be a design issue that should be looked at?

**Comment by allanaaa** [comment]
Note that Mapping is sending a `fieldset` to both Map Browse and to Advanced Search, which we aren't styling well by default or in any of the themes I've seen.

**Comment by zerocrates** [comment]
@allanaaa take a look at branch advanced-search-improvements which moves from a fieldset to a crammed-together field.

Decent possibility themes' styles will mess with this but maybe not: we should be able to set styles to enforce reasonableness if necessary.

**Comment by zerocrates** [comment]
@allanaaa since this change is in, is there any impact to documentation? Possibly screenshots?

**Comment by allanaaa** [comment]
@zerocrates You're ready for a release ASAP? You can go ahead when you're ready, I'll follow up in a day or two.

**Comment by zerocrates** [comment]
I think it'll be a little longer than that before this all gets released.
