### ISSUE TITLE
Testing & Documentation: New scroll wheel zoom options for Mapping page blocks

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#107]
We've added "Scroll wheel zoom" options to the "Map by attachments" and "Map by query" page blocks that control the behavior of the mouse scroll wheel when hovering over a map. There are three options:

- Enabled: scroll wheel zoom is always enabled (after a brief mouse hover) (default)
- Disabled: scroll wheel zoom is always disabled (use in-map controls instead)
- Disabled until map click: scroll wheel zoom is disabled until the map is clicked

Add a map block to a page (as well as a few other blocks so the page scrolls) and test that each option works as expected.

**Comment by allanaaa** [comment]
This appears to work. 

When the map block includes a timeline, clicking inside the timeline (and scrolling, for that matter) does nothing. Is that intended? We only want the map rectangle to work this way?

Can you put some help text in the interface? "Set whether users can zoom with their mouse wheel when hovering over the map, either automatically upon page load or after clicking inside the map." or something.

**Comment by jimsafley** [comment]
Thanks! Yes, we only want the map rectangle to work this way. I'll add the help text.

**Comment by allanaaa** [comment]
Are you planning to add this setting to the "Map Browse" page too?

**Comment by jimsafley** [comment]
No.
