### ISSUE TITLE
Map Browse page doesn't have a title

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Mapping#108]
This page should have a title displaying at the top of the page. Should be in 

```
<h2>
<span class="title">Map Browse (or [Label passed from Navigation settings])</span>
</h2>
```

**Comment by allanaaa** [comment]
It doesn't send a page name to `<head><title>` either.

**Comment by zerocrates** [comment]
Would we be happy with just "Map"?

As the items browse title is similarly just "Items"

**Comment by allanaaa** [comment]
It sends "Map Browse" by default, which users can change with the Label field on the navigation page. I would probably keep the page title and the nav display the same?

**Comment by zerocrates** [comment]
I'm just saying that by analogy to the Item browse, we don't currently have those match: the title there is always Items though the default in the nav is "Browse."

**Comment by allanaaa** [comment]
For the sake of having a user override, I would match them, since nobody seems at all keen to build any more customization into the Map Browse page. But "Map" as a default would be fine I think.
