### ISSUE TITLE
Navbar hidden under map in Foundation

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Mapping#109]
The map seems to have a z-index of 400 while the Foundation menu dropdowns have a z-index of 2. Not sure if this needs to be fixed in the theme or the module!

![foundation-map](https://user-images.githubusercontent.com/28012148/229883894-ab0be119-38d6-464b-89bd-cda3b66d7055.PNG)

**Comment by zerocrates** [comment]
It's _probably_ Mapping that should change here.

Setting `z-index: 0` (and possibly `position: relative` on the map's enclosing div is typically the correct solution here.

**Comment by zerocrates** [comment]
That styling is already provided by the module for `.mapping-block` but probably just needs to be extended to the browse-page map.
