### ISSUE TITLE
Request: Set a site-wide basemap in Site Settings

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Mapping#112]
For aesthetic reasons, it would be nice to set one basemap across an entire site, so that item pages, map browse, and map blocks all have the same visuals. 
Right now the item view maps don't have any customization, only page blocks and the browse page. 

We might also allow sitewide WMS overlays in site settings, although those can be geographically limited, so maybe a warning as well.

**Comment by jimsafley** [comment]
Fixed in 36776e55e2e98c08cfca5f41e5cc4647cbab311f
