### ISSUE TITLE
Map Browse page shows "View item" instead of item title on pins

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Mapping#113]
Map on a page:
![maponhomepage](https://github.com/omeka-s-modules/Mapping/assets/28012148/3aea01a8-ecb4-45c9-ab19-526490205242)

Same site, Map Browse page:
![mapbrowsepage](https://github.com/omeka-s-modules/Mapping/assets/28012148/66b4cd7b-e877-4062-aeaf-9c58b03add79)

It would be nice to see some titles!

**Comment by allanaaa** [comment]
Just for FYI, if you do set some labels and images on markers, it shows like this:

Map Browse page:
![mapbrowsepage2](https://github.com/omeka-s-modules/Mapping/assets/28012148/ea04e8e5-08ee-49e9-9d78-9184f3effb11)

Map on homepage:
![maponhomepage2](https://github.com/omeka-s-modules/Mapping/assets/28012148/c5e00753-a700-4588-871c-9cc17badc374)

**Comment by allanaaa** [comment]
I guess this is somewhat of a duplication of https://github.com/omeka-s-modules/Mapping/issues/68 - not sure what else we want to have more fully configurable.

**Comment by jimsafley** [comment]
All this is how it was designed. As I explain [here](https://forum.omeka.org/t/add-title-to-all-map-markers/10285/4):

> Bear in mind that, unlike Classic’s Geolocation plugin, the Mapping module allows more than one marker per item, which complicates our assumptions about what should go into the popup. Item owners can already modify the individual marker’s label and thumbnail, so we have to consider that as we move forward.

**Comment by jimsafley** [comment]
Fixed in 36776e55e2e98c08cfca5f41e5cc4647cbab311f
