### ISSUE TITLE
Mapping markers + site language

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Mapping#115]
Is there any way to have the Mapping markers load the appropriate language-tagged Item Title or Media Title when a site has a locale selected? This would be in page blocks, and on item view pages.

**Comment by allanaaa** [comment]
Ditto the timeline inside the mapping page block.

**Comment by jimsafley** [comment]
Fixed in 36776e55e2e98c08cfca5f41e5cc4647cbab311f
