### ISSUE TITLE
Mapping adding empty parameters to navigation links

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Mapping#116]
When a new Browse page is added to a site navigation, it's getting an unecessarily long link with some empty mapping parameters. 

To replicate, add a new Browse page with any query (in this case, "Title has any value"). The link added to the navigation will look like:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/item?property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=1&property%5B0%5D%5Btype%5D=ex**&has_markers=&mapping_address=&mapping_radius=&mapping_radius_unit=km**

**Comment by zerocrates** [comment]
I believe it's Javascript used by the Query element/sidebar that removes the "unnecessary"/empty search terms. The Mapping ones showing up here are harmless, but would more ideally be getting removed.

I don't believe we currently have a way for modules to add "cleaning" logic for the elements they add.
