### ISSUE TITLE
Documentation: new geometries, et al. 

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#119]
See [the testing issue](https://github.com/omeka-s-modules/Mapping/issues/117) for new features.

**Comment by allanaaa** [comment]
Notes to self, besides the polygons:

https://github.com/omeka-s-modules/Mapping/issues/118

https://github.com/omeka-s-modules/Mapping/issues/115

https://github.com/omeka-s-modules/Mapping/issues/113

https://github.com/omeka-s-modules/Mapping/issues/112

https://github.com/omeka-s-modules/Mapping/issues/106

https://github.com/omeka-s-modules/Mapping/issues/96

https://github.com/omeka-s-modules/Mapping/issues/68

**Comment by allanaaa** [comment]
@jimsafley Can we change the map interface language? We are introducing "Features" into the vocabulary in the documentation (to mean markers and shapes). But the two interface buttons say "Edit layers" and "Delete layers", and it's not clear what layer refers to. Perhaps "Edit features" and "Delete features" instead?

**Comment by jimsafley** [comment]
I've changed the language to use "feature" instead of "layer".

**Comment by allanaaa** [comment]
Okay, I've:

- removed all mention of Stamen maps
- added shapes
- added a section on site-wide settings including cluster disabling and site-wide base maps
- changed a bunch of language
- updated many screenshots, renamed files
- added the map block for item sets
- updated advanced search and batch edit info
- updated the very outdated map-by-query instructions.

I did NOT test timelines or look at the docs at all; I did not test CSV or edit the doc section at all, since that will be next. 

[The linked PR is ready for review](https://github.com/omeka/omeka-s-enduser/pull/200) @jimsafley @sleon, though I want it to stay in draft until I get a chance to double-check some things on Sharon's installation.

**Comment by allanaaa** [comment]
Sharon updated her install and no data was lost, so I'm happy with this. 

https://github.com/omeka-s-modules/Mapping/issues/122 is the only thing outstanding before a new release, I believe, and I'm happy with that too.

**Comment by jimsafley** [comment]
There is one additional change that we should possibly add before a new release. The [paginate-map-browse](https://github.com/omeka-s-modules/Mapping/compare/master...paginate-map-browse) branch introduces pagination to the map browse page, where before there was a hard limit of 5000 items. It's a relatively small change, but it would need testing and styling. What do you think?

**Comment by allanaaa** [comment]
> There is one additional change that we should possibly add before a new release. The [paginate-map-browse](https://github.com/omeka-s-modules/Mapping/compare/master...paginate-map-browse) branch introduces pagination to the map browse page, where before there was a hard limit of 5000 items. It's a relatively small change, but it would need testing and styling. What do you think?

I like it, but it's not working for me. I've got a map browse setting of 23. The map is showing 23 items, but also indicating that only 23 items in the whole site have map data. (It should be 346.)

<img width="720" alt="Screenshot 2024-05-27 at 12 48 12" src="https://github.com/omeka-s-modules/Mapping/assets/28012148/af3ae929-a4f2-44e9-a2bc-e5d78ec082e2">

<img width="718" alt="Screenshot 2024-05-27 at 12 47 57" src="https://github.com/omeka-s-modules/Mapping/assets/28012148/28e4bdbc-b8ad-4fe7-a9f9-f2b906abab20">

The buttons could be centered under the map? Or appear under the page title, more in the vein of other browse pages?

**Comment by jimsafley** [comment]
I forgot to mention that this feature requires you to check out the [set-correct-total-scalar-results](https://github.com/omeka/omeka-s/tree/set-correct-total-scalar-results) branch on core.

As for the pagination's position: @kimisgold Do you have thoughts on where pagination should go on the map browse page?

**Comment by allanaaa** [comment]
Gotcha. This mostly looks good now - waiting to combine it with the edge-padding feature so we don't get pagination that looks like this:

<img width="1039" alt="Screenshot 2024-06-03 at 11 07 06" src="https://github.com/omeka-s-modules/Mapping/assets/28012148/4e43e7d6-dcc5-49af-ad6f-2a509f6e19be">

Looks fantastic with the Mall items of course. 
<img width="1029" alt="Screenshot 2024-06-03 at 11 09 29" src="https://github.com/omeka-s-modules/Mapping/assets/28012148/2e3deda8-899b-40af-8ca8-a9d3e79084bc">

I'll pop this new setting in the docs while you two work out some styling. And if you can merge everything for the new release, I'll take one last look to make sure it all works.

**Comment by jimsafley** [comment]
I've merged the padding and pagination branches into master. @kimisgold When you get a chance, I'd like your opinion on the styling questions we have above.

**Comment by kimisgold** [comment]
I've provided some default pagination styles that should work for most themes. I'll be doing individual theme updates where necessary:

* Foundation (has custom pagination markup)
* Center Row and The Daily's pagination looks okay, but the search form underneath needs styling help.

I'm also going to tag @nelsonamaya82 for Lively and Freedom updates, as they use custom mapping views that need to include the new pagination.

**Comment by jimsafley** [comment]
Thanks, @kimisgold.

@allanaaa Can we close this issue?

**Comment by allanaaa** [comment]
Pagination looks good in most places. In Center Row I'm getting this:

<img width="1169" alt="Screenshot 2024-06-05 at 11 03 14" src="https://github.com/omeka-s-modules/Mapping/assets/28012148/9bf81db5-e2e8-4456-990b-5bfff05fd09c">

**Comment by kimisgold** [comment]
Yup, that's the theme-specific issue about the search form I'll address today. The Daily has similar problems I'll address.

**Comment by allanaaa** [comment]
In Foundation Seafoam I'm getting significant problems with the map browse page: 

<img width="1229" alt="Screenshot 2024-06-05 at 11 04 42" src="https://github.com/omeka-s-modules/Mapping/assets/28012148/5c38728e-20e6-44e3-9159-e45c7eb3d2c3">

**Comment by allanaaa** [comment]
Sorry, didn't read your comment!

**Comment by allanaaa** [comment]
Okay, I'm going to assume you two have all this styling and order-of-operations stuff in hand, so sure, this can be closed. I'll add the pagination to the docs PR.
