### ISSUE TITLE
Testing: Add GeoJSON to mapping blocks

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#120]
~The [map-by-geojson-block](https://github.com/omeka-s-modules/Mapping/compare/master...map-by-geojson-block) branch introduces the "Map by GeoJSON" block layout. Page builders can now add maps to their pages using [GeoJSON](https://geojson.org/) instead of geocoded items.~

The [map-by-groups-block-plus-optimization](https://github.com/omeka-s-modules/Mapping/compare/master...map-by-groups-block-plus-optimization) branch introduces a way for page builders to add features to their maps using GeoJSON.

To test this feature, ~add a "Map by GeoJSON" block layout to a page,~ enter any GeoJSON to a "Map by" block, save the page, and view the resulting map on the public page. You can find many GeoJSON examples online. A helpful source I use is the [List of open GeoJSON datasets](https://open-innovations.org/data/geojson.html) on the Open Innovations website.

In addition to the normal "Default view" and "WMS overlays" sections, the block layout includes a "GeoJSON" section that has several fields:

- **Label property key**: Enter the GeoJSON property key used for the popup label, if any.
- **Comment property key**: Enter the GeoJSON property key used for the popup comment, if any.
- **Show GeoJSON property list?**: Do you want to show the GeoJSON property list if available?
- **GeoJSON**: Enter the GeoJSON

To understand the first three inputs, it's important to note that GeoJSON often contains a list of properties, which are just arbitrary key/value pairs that describe a geolocated feature. So if there's a "Title" property for every feature, the user could enter "Title" in the **Label property key** field, and that will be the feature's popup label.

**Comment by allanaaa** [comment]
This appears to work at a basic level:

<img width="1193" alt="Screenshot 2024-07-31 at 13 26 24" src="https://github.com/user-attachments/assets/78663ecb-98f1-4adc-b9e0-f7a9996f01f4">

1) I found the admin side obtuse and it took some experimenting to figure out what all this meant. Help text could be more like

- Label property key: If you wish to feature one value as each map feature's pop-up title, enter the property name here. 
- Comment property key: If you wish to feature one value as each map feature's pop-up text, enter the property name here.
- Show GeoJSON property list?: Check this if you wish map pop-ups to show all available information about each point.
- GeoJSON: Enter the GeoJSON code in full. (Probably could make this even more obvious....)

2) "Enter the GeoJSON" - could users also have the option to paste in a link to scrape, instead of manually copy-pasting this content? Or is the assumption users will more likely be putting in their own work from a local file? 

3) Can a user enter in multiple chunks of geoJSON here? If I wanted to combine 2 or more of the datasets from that link, can I just copy-paste them all in succession and have them all display on one map?

4) Might there be any geoJSON in the world that sends media to display in the pop-up? Is that possible?

**Comment by allanaaa** [comment]
5. Is there a way to incorporate Omeka items into the same map with the geoJSON? Could a user combine non-item features with item features using geoJSON code? Or would we need to add more fields to do a query or attachments?

**Comment by allanaaa** [comment]
6. Could we incorporate any error messages here? Soemthing that validates the inputted code when you save the page, maybe? I did a few straight copy-pastes from your source and with some code the map wouldn't load on the public page.

**Comment by jimsafley** [comment]
I've integrated the GeoJSON feature into the "Map by attachments" and "Map by query" block layouts. It is now ready for testing in the [map-by-groups-block-plus-optimization](https://github.com/omeka-s-modules/Mapping/compare/master...map-by-groups-block-plus-optimization) branch. You may delete the [map-by-geojson-block](https://github.com/omeka-s-modules/Mapping/compare/master...map-by-geojson-block) branch, but we'll continue discussing the feature on this issue.

**Comment by jimsafley** [comment]
> "Enter the GeoJSON" - could users also have the option to paste in a link to scrape, instead of manually copy-pasting this content? Or is the assumption users will more likely be putting in their own work from a local file?

I see the potential value, but it's probably a feature for a future release. For now the assumption is users will be entering in the GeoJSON themselves.

> Can a user enter in multiple chunks of geoJSON here? If I wanted to combine 2 or more of the datasets from that link, can I just copy-paste them all in succession and have them all display on one map?

I think it's reasonable to only accept one dataset at a time. The benefits don't outweigh the additional complexity of allowing an indefinite amount of datasets. Users can always combine them by hand. Maybe for a future release.

> Might there be any geoJSON in the world that sends media to display in the pop-up? Is that possible?

Possibly, but until we have a real use case from someone using this feature, we don't have much to go on.

> Is there a way to incorporate Omeka items into the same map with the geoJSON? Could a user combine non-item features with item features using geoJSON code? Or would we need to add more fields to do a query or attachments?

A good idea. I've implemented this. Look at the "GeoJSON" section in the "Map by attachments" and "May by query" block layouts.

> Could we incorporate any error messages here? Soemthing that validates the inputted code when you save the page, maybe? I did a few straight copy-pastes from your source and with some code the map wouldn't load on the public page.

Validating GeoJSON client-side is tricky. Perhaps just validating for JSON would catch most errors. I'll look into it.

**Comment by allanaaa** [comment]
In both the Query and Attachments blocks, you've got "Label property key" twice - the second one should be "Comment property key" instead I think. 

<img width="709" alt="Screenshot 2024-11-05 at 09 42 53" src="https://github.com/user-attachments/assets/34b5ac0a-eeb8-474c-9428-88604d2f7109">

**Comment by allanaaa** [comment]
Is there any way of displaying the geoJSON pins/clusters differently than our Omeka items? Maybe just different colour profiles for each?

**Comment by jimsafley** [comment]
> In both the Query and Attachments blocks, you've got "Label property key" twice - the second one should be "Comment property key" instead I think.

Oops. Fixed.

> Is there any way of displaying the geoJSON pins/clusters differently than our Omeka items? Maybe just different colour profiles for each?

We plan to make feature styles configurable in a future release, so this will have to wait.

**Comment by allanaaa** [comment]
1) Both the Query and Attachments blocks aren't loading their selected basemaps. The site-wide basemap setting is working when used, but individual maps won't. (The chosen basemaps are showing on the admin side for each block, though.)

2) I thought Timeline and geoJSON were working fine together (noted in the docs that geoJSON items won't appear on the timeline). ~But I think that usually when you scroll through the timeline, the map zooms in all the way to the feature of the individual item in focus? It's not doing that right now.~ Ah, I see, the "Fly to: Default view" isn't the item's "default view", it's whatever the map originally loaded with. Maybe there's a better term for that. 
http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/maps-test

**Comment by allanaaa** [comment]
3. These coloured blobs when the timeline-based map starts zooming in (with the "fly to" set to something high) aren't ideal.

https://github.com/user-attachments/assets/e1de6131-1167-4cd2-afa8-99a07404efc6

**Comment by jimsafley** [comment]
> Both the Query and Attachments blocks aren't loading their selected basemaps. The site-wide basemap setting is working when used, but individual maps won't. (The chosen basemaps are showing on the admin side for each block, though.)

It should be fixed now. The block's basemap provider should take priority over the site's basemap provider.

> I thought Timeline and geoJSON were working fine together (noted in the docs that geoJSON items won't appear on the timeline).

Yes, the GeoJSON features will only appear on the initial map, before the user navigates to individual events. I don't expect many users will add GeoJSON when using a timeline.

> These coloured blobs when the timeline-based map starts zooming in (with the "fly to" set to something high) aren't ideal.

Yes, that's not ideal. Perhaps it'll get fixed in a later release.

**Comment by allanaaa** [comment]
The basemaps issue seems to be fixed. 

There is a handful of basemaps that aren't loading: both HikeBike ones, Esri.DeLorme, and Esri.OceanBasemap. 

When I selected one of them and saved the page, two blocks somehow deleted themselves. I can't recreate it, but that's a pretty big bug if we can find it.

**Comment by jimsafley** [comment]
> When I selected one of them and saved the page, two blocks somehow deleted themselves. I can't recreate it, but that's a pretty big bug if we can find it.

Selecting a base map is certainly not the reason, but this is definitely alarming. It may have something to do with our new page layout system? Are you doing anything interesting with the layout?

**Comment by allanaaa** [comment]
I had a new page in normal flow with 3 Mapping blocks, each set up similarly to test the geoJSON, timeline, basemaps, etc. I'll mess around a bit more with it. 

On the visual side, the geoJSON map pop-ups (when displaying all available information) are loading a height and scroll setting inline that don't seem necessary - where is that coming from? Could height and overflow both be set to "auto" instead? And can this be in a CSS file rather than inline? 
<img width="993" alt="Screenshot 2024-11-12 at 13 54 06" src="https://github.com/user-attachments/assets/8e50e69d-4100-46a8-95eb-a11150f45aa2">

**Comment by jimsafley** [comment]
> On the visual side, the geoJSON map pop-ups (when displaying all available information) are loading a height and scroll setting inline that don't seem necessary - where is that coming from? Could height and overflow both be set to "auto" instead? And can this be in a CSS file rather than inline?

@kimisgold Can something be done about this? You can reproduce by pasting [this GeoJSON](https://raw.githubusercontent.com/openlayers/openlayers/refs/heads/main/examples/data/geojson/polygon-samples.geojson) into a block's GeoJSON field, check "Show GeoJSON property list?", then go to the public page and click on a polygon. This is on the `map-by-groups-block-plus-optimization` branch. Don't forget to pull first.

**Comment by kimisgold** [comment]
@allanaaa i'm having trouble reproducing this in Safari, Chrome, and Firefox for iOS. Can you provide me with a browser and live link?

**Comment by allanaaa** [comment]
It's this link from earlier in the thread:

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/maps-test

Any of the UK-based pins are the geoJSON ones. You'll see the inline code says "`<dl style="height: 200px; overflow: scroll;">`" which is what we want to get rid of.

It looks the same to me in Chrome and in Firefox:

<img width="676" alt="Screenshot 2024-11-18 at 18 11 15" src="https://github.com/user-attachments/assets/a51ca3ba-2ddd-42b9-93e2-d55b63093745">

<img width="740" alt="Screenshot 2024-11-18 at 18 11 24" src="https://github.com/user-attachments/assets/8ed091a5-beec-4cc8-9611-358129809316">

**Comment by zerocrates** [comment]
Just to be clear, Mapping is intentionally doing this: 

https://github.com/omeka-s-modules/Mapping/blob/map-by-groups-block-plus-optimization/asset/js/MappingModule.js#L193

I assume the idea is to avoid really big marker windows when there's lots of properties. It can certainly be a class instead, and `max-height` instead of `height` and `overflow: auto` or `overflow-y: auto` instead of `overflow: scroll` are probably enough to avoid the negatives for stuff that's smaller.

**Comment by kimisgold** [comment]
Once again belatedly realized I wasn't having scrollbar issues due to macOS settings.

I've set a class and applied @zerocrates's suggestions. It should be ready to pull for a look.

**Comment by allanaaa** [comment]
Looks great, thanks!

I think I'm happy with this feature - it looks good in both page blocks. 

Maybe some minor admin-side language tweaking. I did suggest this earlier:

>     Label property key: If you wish to feature one value as each map feature's pop-up title, enter the property name here.
>     Comment property key: If you wish to feature one value as each map feature's pop-up text, enter the property name here.
>     Show GeoJSON property list?: Check this if you wish map pop-ups to show all available information about each point.
>     GeoJSON: Enter the GeoJSON code in full. (Probably could make this even more obvious....)

But a more modest version might be:

Label property key
Enter the GeoJSON property key to use for the popup label, if desired.
Comment property key
Enter the GeoJSON property key to use for the popup comment, if desired.
Show GeoJSON property list?
Do you want to show all the available GeoJSON properties in the popup?

The only other thing oustanding is whether you can get any error validation in there - 
 
>     Could we incorporate any error messages here? Soemthing that validates the inputted code when you save the page, maybe? I did a few straight copy-pastes from your source and with some code the map wouldn't load on the public page.
> 
> Validating GeoJSON client-side is tricky. Perhaps just validating for JSON would catch most errors. I'll look into it.

**Comment by jimsafley** [comment]
I've changed the field info and added JSON validation. Would you please test validation? You should see an alert when a GeoJSON field has invalid JSON.

**Comment by allanaaa** [comment]
That works! I hacked off the beginning of the geoJSON, and then the end, and some random chunks in the middle, so that should cover most copy-paste errors. With that and text change you've done, this may be finished?

Can you make a documentation issue and list the things that need to be covered for the next release, just in case I miss any little stuff?

**Comment by jimsafley** [comment]
Yes, I'll create a documentation issue once I'm confident all features are completed and tested. Should be by the end of next week.
