### ISSUE TITLE
Add buffer to "contain all" maps

### ISSUE THREAD

**Issue by allanaaa** [omeka-s-modules/Mapping#122]
In the 2.0.0-alpha1 version we're about to release as per #119, the Map Browse page and the page blocks seem to just barely contain all features, right on the edge, which means it's not so graceful and the pins can be blocked by the map navigation buttons. 

<img width="1108" alt="Screenshot 2024-05-21 at 11 24 39" src="https://github.com/omeka-s-modules/Mapping/assets/28012148/5a244a1b-f2f6-450d-9cf5-c0c52512b197">

<img width="1114" alt="Screenshot 2024-05-21 at 11 25 06" src="https://github.com/omeka-s-modules/Mapping/assets/28012148/c7a90308-82fe-4a55-85d9-cdc85248fec7">

Can you add some buffer space to this somehow?

**Comment by jimsafley** [comment]
In the [add-padding-to-bounds](https://github.com/omeka-s-modules/Mapping/compare/master...add-padding-to-bounds) branch I've added padding to the map browse page. Take a look and see if it works and if it's sufficient.

**Comment by allanaaa** [comment]
Big difference!

<img width="1045" alt="Screenshot 2024-05-22 at 15 54 03" src="https://github.com/omeka-s-modules/Mapping/assets/28012148/ae020ef4-0b3a-417b-b925-d535a54f5ec7">

<img width="1067" alt="Screenshot 2024-05-22 at 15 54 23" src="https://github.com/omeka-s-modules/Mapping/assets/28012148/7176c217-8ba3-441c-90ed-0166a1b3668d">

I'm fine with this as it is, but you could probably dial it back a bit if you want.

**Comment by jimsafley** [comment]
I've reduced the padding. You may not see a difference because of the way Leaflet calculates bounds, but "fit features into view" should now be optimized to never show features behind control overlays.
