### ISSUE TITLE
Styling is wonky on item search by geolocation options in right drawer panel

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/Mapping#125]
Seen in the context of setting a universe of resources for a site.
![Screenshot 2024-10-22 at 15-50-42 Resources · Sites · Testing](https://github.com/user-attachments/assets/70228d7c-8ec8-474b-8b95-e861831945f9)

**Comment by jimsafley** [comment]
@kimisgold Would you mind looking at this? The "Search by geographic location" fields look fine on the advanced search page, but display oddly when in a sidebar. The CSS is in `css/mapping-advanced-search.css`.

**Comment by kimisgold** [comment]
This is going to have to be a fix to the core, as there's no way to attach css when the form is being loaded into the sidebar with ajax. It's a good pattern to have styles in place for, scenarios in which a fieldset might have subfields within the inputs.

**Comment by kimisgold** [comment]
@sharonmleon would you mind pulling the latest changes in the core and testing the styles in the `style-inputs-sub-fields` branch? that should address the issue here.

**Comment by sharonmleon** [comment]
@kimisgold This is fixed and should be good to be merged. Sorry I didn't see the notification sooner.
