### ISSUE TITLE
Testing: Overlays

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#127]
The `map-by-groups-block-plus-optimization` branch replaces the "WMS Overlays" section with an "Overlays" section in the "Map by attachments" and "Map by query" page blocks. The "Overlays" section allows page builders to add two types of overlays to their maps:

- Web Map Service (WMS)
- IIIF Georeference Annotation

This will require a module upgrade. But before upgrading, make sure you have several WMS overlays already saved. After you've upgraded, they should be moved to the new "Overlays" section.

To test this, add a "Map by attachments" or "Map by query" block, open the "Overlays" section, select an overlay type, complete the form, save the overlay, and save the page. Check that the public map includes the overlay in the "Overlays" list, and that the overlay appears on the map when clicked. Add more overlays and edit/delete/move them. The overlay list on the public map should reflect the order you set.

A good source for WMS overlays is [Map Warper](https://mapwarper.net/maps?show_warped=1). Browse the rectified maps, select one, go to the "Export" tab, and copy the "WMS Capabilities URL" link address. Use that URL as the WMS base URL.

A good source for IIIF Georeference Annotation overlays is [Allmaps](https://viewer.allmaps.org/), specifically the examples at the bottom of that page. Go to those examples and copy the URL in the text input. Use that URL as the IIIF URL.

**Comment by allanaaa** [comment]
Sorry but because I'm updating from the branch to check on other issues, this 

> make sure you have several WMS overlays already saved. After you've upgraded, they should be moved to the new "Overlays" section.

can't be verified. I'm sure I must have had a WMS overlay in a block on one of my sites, but I don't see anything carried over. Perhaps we can get @katknow or @kimisgold to check this on their own sites?

**Comment by jimsafley** [comment]
> I'm sure I must have had a WMS overlay in a block on one of my sites, but I don't see anything carried over. 

Hmm. It's a simple upgrade, so I'm surprised. The most thorough way to test this is:

1. Uninstall Mapping
2. Checkout the `master` branch
3. Add a few WMS overlays to a few Mapping blocks
4. Checkout the `map-by-groups-block-plus-optimization` branch
5. Upgrade Mapping

Obviously that will delete all your previous Mapping data, which isn't optimal I admit.

**Comment by allanaaa** [comment]
I added one overlay, saved the page, then immediately added a few more. When I saved I got that "CSRF token" error, next to the "successfully saved" bar, and the most recent overlay additions did not save. 

<img width="701" alt="Screenshot 2024-11-28 at 12 51 13" src="https://github.com/user-attachments/assets/873139b5-fba5-434e-b4ab-9ad549cbeae8">

**Comment by allanaaa** [comment]
WMS overlays are displaying fine. 
IIIF overlays seem fickle. I can see them fine on Firefox in a private window, but not when logged-in, and not in Chrome. 

Chrome console (when I click the "Fly to overlay" button):

> index.js:9 
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
>     at yc (index.js:9:44)
>     at qn (index.js:24:24)
>     at kf.loadImageInfo (WarpedMap.js:327:59)
>     at BaseRenderer.js:42:20
>     at Array.map (<anonymous>)
>     at Hp.loadMissingImageInfosInViewport (BaseRenderer.js:42:7)
>     at Hp.render (WebGL2Renderer.js:409:52)
>     at Pn._update (WarpedMapLayer.ts:947:19)
> 
> index.js:9 
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
>     at yc (index.js:9:44)
>     at qn (index.js:24:24)
>     at kf.loadImageInfo (WarpedMap.js:327:59)
>     at BaseRenderer.js:42:20
>     at Array.map (<anonymous>)
>     at Hp.loadMissingImageInfosInViewport (BaseRenderer.js:42:7)
>     at Hp.render (WebGL2Renderer.js:409:52)
>     at Pn._update (WarpedMapLayer.ts:947:19)
> 
> index.js:9 
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
>     at yc (index.js:9:44)
>     at qn (index.js:24:24)
>     at kf.loadImageInfo (WarpedMap.js:327:59)
>     at BaseRenderer.js:42:20
>     at Array.map (<anonymous>)
>     at Hp.loadMissingImageInfosInViewport (BaseRenderer.js:42:7)
>     at Hp.render (WebGL2Renderer.js:409:52)
>     at Pn._update (WarpedMapLayer.ts:947:19)
>     at Pn._resized (WarpedMapLayer.ts:854:10)

<img width="843" alt="Screenshot 2024-11-28 at 13 01 45" src="https://github.com/user-attachments/assets/a56d909d-3759-41bb-ba71-59718c20523b">

**Comment by allanaaa** [comment]
The "Fly to overlay" button does re-centre the map to the correct area even when the overlay itself doesn't display, so something there is working....

http://dev.omeka.org/amayer/amayer-s/omeka-s/s/my-omeka-s-site/page/maps-test (first map)

**Comment by jimsafley** [comment]
> IIIF overlays seem fickle. I can see them fine on Firefox in a private window, but not when logged-in, and not in Chrome.

The overlays will be fickle because we're at the mercy of services that are out of our control. I've tested them and they all eventually work. It's not optimal, but unfortunately there's nothing I can do. It's probably a good idea to mention this to the end user in documentation.

**Comment by zerocrates** [comment]
The error here looks like its actually happening when you're not viewing the page with HTTPS: your link is a plaintext-http link, but browsers will tend to sometimes decide for you that you wanted https when copy-pasting or opening in incognito, so i think you just happen to be using the https URL when looking in a private window.

**Comment by allanaaa** [comment]
Oh, great catch! Yep, worked like a charm in both Firefox and Chrome. I wonder how I got off https.... 

I did get that CSRF token error once more, immediately after saving the page and trying to make one more change. This time the only change I tried to make was unchecking one of the overlays as the default. 

I think the label should be a required field for overlays. 

And, I think the "Fit all features on the map within one view" button probably shouldn't appear if the timeline is enabled, or rather it should only fit all visible/contemporaneous events (& overlays) rather than all features (since 99.9% of them are invisible at any one time).

**Comment by jimsafley** [comment]
> I did get that CSRF token error once more, immediately after saving the page and trying to make one more change.

I'm not sure what's going on here, but it's likely not an issue with Mapping. We'll look into it at the core level.

> I think the label should be a required field for overlays.

I just pushed a change that makes the label field required. Try it out.

> And, I think the "Fit all features on the map within one view" button probably shouldn't appear if the timeline is enabled,

I've disabled the control when the timeline is active. Try it out.

**Comment by jimsafley** [comment]
@allanaaa I've added an "Overlay mode" setting to the overlays section. The default mode ("Exclusive") is the default behavior we're already used to. The new mode ("Inclusive") allows more than one overlay to be added to the map at one time. Try it out. The one caveat is that selecting "Inclusive" will disable the opacity/fly-to controls.

**Comment by jimsafley** [comment]
@allanaaa I've taken out the "GeoJSON" section and folded it into the "Overlays" section. Now users can add GeoJSON as overlays. Try it out.

**Comment by allanaaa** [comment]
The overlays set to inclusive appear perfectly, including a combo of IIIF and WMS and geoJSON. 

1) Labels are required, which is great - but can we have an interface indicator for that? A red asterisk like we use in other places? 

2) The geoJSON works as an overlay but the map pins aren't clustering the way they used to / the way item pins do:

<img width="677" alt="Screenshot 2024-12-06 at 14 33 37" src="https://github.com/user-attachments/assets/2be37118-11cf-4aaf-995c-7e2d80577419">

This is regardless of the site-wide cluster settings. 

3) I no longer see the "Fit all features" button at all when a map includes a timeline, even on the default view when all pins are visible. I was thinking to turn it off only when we're on a specific point-in-time. Not sure if that's technically possible.

**Comment by jimsafley** [comment]
> Labels are required, which is great - but can we have an interface indicator for that? A red asterisk like we use in other places?

I pushed a change that displays the red asterisk.

> The geoJSON works as an overlay but the map pins aren't clustering the way they used to / the way item pins do:

We figure that users will largely use GeoJSON to display polygons that should not be clustered. In a future release we'll look into adding more granularity to cluster settings.

> I no longer see the "Fit all features" button at all when a map includes a timeline, even on the default view when all pins are visible. I was thinking to turn it off only when we're on a specific point-in-time. Not sure if that's technically possible.

Yeah, that's a tough one. I think I'll hold off on this until someone complains.

**Comment by allanaaa** [comment]
Okay, I think this is looking pretty good for now! 

Are you planning to add overlays to the Map By Groups block as well?

**Comment by jimsafley** [comment]
> Are you planning to add overlays to the Map By Groups block as well?

Not yet. I'm not sure what users expect from overlays in an interface that essentially displays two different maps. once I have a better idea (and have the time), I'll consider it.
