### ISSUE TITLE
Map Browse page for sites not picking up CSVImported items with geolocation

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/Mapping#23]
The items are getting mapping data attached to them individually, but when their added to a site pool and then the map browse page is added to that site it only displays items that have been geolocated by hand.

**Comment by jimsafley** [comment]
I can't reproduce this. I imported the CSV, mapping the "lat" column to Map:Latitude and the "long" column to Map:Longitude. I then attached some items to a Map block. I see the markers on the public map. Check that you correctly mapped the columns and it's helpful to set a Default View when configuring the block.

**Comment by sharonmleon** [comment]
Did you get many items at each site? Or just one? 

Also, the page that I'm using is not a single page with a map block added, but rather the Map Browse that is available (autobuilt) through the Navigation interface.

**Comment by jimsafley** [comment]
Ah, I was testing the Map page block, not the Map Browse. What I'm seeing are four different sites, at which are many markers with identical coordinates (the dark shadows are unmistakable). If anything, this shows me that the public maps need some kind of clustering to prevent markers with identical coordinates from overlapping.

![whoameka](https://cloud.githubusercontent.com/assets/141955/18572298/fc6ee136-7b87-11e6-9a53-a5619c875087.png)

**Comment by sharonmleon** [comment]
Okay. I was confused because I was only able to click on one -- which made it seem like they were replacing each other rather than piling up. 

Could we do a pin count, like we did with the Mall Histories stuff?

**Comment by jimsafley** [comment]
Yes, with https://github.com/Leaflet/Leaflet.markercluster I'll create an issue.

**Comment by sharonmleon** [comment]
Thanks!

**Comment by jimsafley** [comment]
@sharonmleon Pull from master and try out the marker clustering. If that works, is this issue resolved?

**Comment by sharonmleon** [comment]
I seem to have broken something about my ability to add new pages to my site, but this fix works well. Thank you.
