### ISSUE TITLE
No maps on public side

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Mapping#30]
On a page with one item with mapping data, added via Item with metadata, a map does not appear on the public side.

**Comment by jimsafley** [comment]
That layout only renders the item's values, item sets, and media. Since the map is none of these things, it's not possible to include it. I'm honestly surprised the layout doesn't link to the item show page, where the map is included.

**Comment by patrickmj** [comment]
not sure we can put out a release candidate without this

**Comment by zerocrates** [comment]
"item with metadata" is always going to be a problematic block just by its very nature

**Comment by jimsafley** [comment]
The only viable solution I see is to include a link to the item show page. But I'm not sure why it was left out in the first place.

**Comment by patrickmj** [comment]
ok. not intuitive, but I see the mechanism to make display happen. @mebrett has put in some good documentation, so I'm no longer worried.
