### ISSUE TITLE
Default view settings not set

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Mapping#34]
On the admin side, creating the Mapping block and setting default view port, saving the page and going back to default view, the intended viewport is not preserved.

On public side, it looks like the default viewport is at the most zoomed-in level.

**Comment by jimsafley** [comment]
I'm intermittently seeing what you describe on the admin side. The map is centered correctly but one zoom level away from where it was previously set. The inconsistency may be a product of our use of bounds to set the default view, but I've found no way to reproduce the bug consistently. There may be a strange interaction between the map loading and the user setting default bounds. 

The public side looks okay on my installation. It's consistently loading the map in *approximately* the correct coordinates/zoom level, as is expected when bounds are set for default view.
