### ISSUE TITLE
Unable to add Item with Mapping data when role is less than Site Admin

### ISSUE THREAD

**Issue by kernsb** [omeka-s-modules/Mapping#36]
I am finding that I am unable to add an Item that includes Mapping data when the Role for the user is set to anything less than Site Administrator (Author, Reviewer, Editor). When attempting to do so, users with lesser roles receive a "Forbidden" error.

To make sure this wasn't just my installation, I duplicated the issue in the official Demo Sandbox. I set the omekasdemo3 account to the Author role, logged in to it, attempted to add an Item with Mapping data, and received "Forbidden".

Thanks for any help. We have a number of students (Purdue University) piloting this for a course project that would love to be able to utilize this feature.

![capture](https://user-images.githubusercontent.com/8202646/31421350-f0ca8248-ae14-11e7-9b09-37c01e066683.PNG)

![capture2](https://user-images.githubusercontent.com/8202646/31421356-f7c0dcaa-ae14-11e7-9c72-c15d36c6ddd5.PNG)

**Comment by patrickmj** [comment]
Just to make sure I see what's happening, does this only happen when adding Mapping data? Or any item creation when in those lesser roles?

**Comment by kernsb** [comment]
It is only when the item being added by those roles includes Mapping data. If you add all other data the same, but leave off the mapping data, the item creates successfully, as expected.

Brandon Kerns


On Oct 11, 2017, at 8:45 AM, Patrick Murray-John <notifications@github.com<mailto:notifications@github.com>> wrote:


Just to make sure I see what's happening, does this only happen when adding Mapping data? Or any item creation when in those lesser roles?

-

**Comment by patrickmj** [comment]
Thanks. That helps a lot. It might be an ACL problem specific to Mapping, or it might indicate a broader problem with how modules interact with core. (or something else, as always!) Those are just my first guesses, but things for us to look in to.
