### ISSUE TITLE
Option to store geolocation data as Dublin Core dcterms:spatial

### ISSUE THREAD

**Issue by giocomai** [omeka-s-modules/Mapping#43]
As far as I understand, geolocation data added through this module is apparently not stored along with other metadata, with a standard Dublin Core (or other) reference.

Wouldn't it be nice to give the possibility to store this data, e.g. in dcterms:spatial?

This could also, for example, facilitate integration with the [Storymap module](https://github.com/agile-humanities/agile-storymap).

As I see it, now one would be supposed to create the map with this module, and then again use another service to find the coordinates, and add them among metadata. 

If there is already a way to do this, I could not find it [in the documentation](https://omeka.org/s/docs/user-manual/modules/mapping/).

**Comment by Daniel-KM** [comment]
Last version of module [DataType Geometry](https://gitlab.com/Daniel-KM/Omeka-S-module-DataTypeGeometry) allows to sync properties and mapping data (in one way or both).

**Comment by Daniel-KM** [comment]
And it has a special datatype to manage latitude and longitude with a normalized way.
