### ISSUE TITLE
Performance issues with 100K+ located items

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#44]
See this forum post: https://forum.omeka.org/t/issue-with-mapping-module/8037

**Comment by zerocrates** [comment]
They're reporting running out of memory on Resource Templates... does Mapping do anything there?

**Comment by jimsafley** [comment]
Yes, Mapping hits the Resource Templates page, but it shouldn't. `Module::cacheItemMappingData()` listens to `api.search.post` and `api.read.post` on `Omeka\Api\Adapter\ItemAdapter`. I'm sure this is the culprit, and I'm sure we can find a better way to cache mapping data only when it's needed.

**Comment by jimsafley** [comment]
Fixed in release v1.1.1
