### ISSUE TITLE
Styling questions

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/Mapping#47]
After playing with the time-mapper (https://github.com/omeka-s-modules/Mapping/tree/timeline) some I have questions about possible styling:

- Is it possible to shift the panes of the display? The horizontal panels seem kind of restrictive. So perhaps a vertical column of the item data on the left and a split pane on the right with the timeline on top and the map on the bottom?
- Can we control what kind of content is in the map bubble? 
- Can the content pane with a file open a lightbox with a larger file or a player for media?
- What are the theming possibilities? The current implementation is really washed out, as it is in the Knightlab versions. (http://52.202.180.75/horse/s/test-site/page/welcome)

@jimsafley @kimisgold

**Comment by jimsafley** [comment]
> Is it possible to shift the panes of the display? The horizontal panels seem kind of restrictive. So perhaps a vertical column of the item data on the left and a split pane on the right with the timeline on top and the map on the bottom?

TimelineJS provides no option to decouple the slide panel (which contains the item data) from the timeline navigation. Perhaps @kimisgold can find a way to do it [using CSS](https://timeline.knightlab.com/docs/overriding-styles.html).

> Can we control what kind of content is in the map bubble?

The marker popup content is currently hard-coded in `view/common/block-layout/mapping-block.phtml`, so it is not customizable. We could explore making it customizable. What do you have in mind?

> Can the content pane with a file open a lightbox with a larger file or a player for media?

I suppose this is possible. I think this would be part of the larger discussion of making the popup content customizable.

> What are the theming possibilities? The current implementation is really washed out, as it is in the Knightlab versions.

We can override the styles. TimelineJS documents their [CSS selectors](https://timeline.knightlab.com/docs/overriding-styles.html).

**Comment by kimisgold** [comment]
> Is it possible to shift the panes of the display? The horizontal panels seem kind of restrictive. So perhaps a vertical column of the item data on the left and a split pane on the right with the timeline on top and the map on the bottom?

TimeMapper itself controls too much of the layout via JS for me to override with CSS. There might be some configuration options I can work with to do something about the layout, but at the moment, it looks like it's more trouble than it's worth.

> Can we control what kind of content is in the map bubble?
> Can the content pane with a file open a lightbox with a larger file or a player for media?

Yes, the theme can provide custom bubble content by creating an overriding mapping block, and we can probably do that lightbox and media player.

> What are the theming possibilities? The current implementation is really washed out, as it is in the Knightlab versions.

We can style the timeline. I've done a few color adjustments to start.
