### ISSUE TITLE
Testing: timeline map

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#49]
The `timeline` branch introduces the option to add a timeline to a public Map block. This feature requires the NumericDataTypes module and at least one item that has a Timestamp or Interval value.

To test this you'll need to create a Resource Template that includes a Timestamp (or Interval) property. Then you'll need to create a few items that use the template, each setting a different NumericDataTypes value. Make sure to add Mapping markers to these items as well.

Then, in a site, edit a page and add a Map block. You should see the new "Timeline" section. Add "Title headline" and "Title text" and set a "Property" (you should see your template property in the menu). Make sure to attach all your items to the block and then save.

Go to the public page and you should see a timeline on top of your map. Cycle through the timeline events and the map should fly to the boundaries of the item's marker(s).

**Comment by mebrett** [comment]
Here's what it looks like: http://dev.omeka.org/mebrett/testomekas/s/publicviews/page/maps 

NB for items with two locations (like the last item April 21, 1819) it zooms out to show both markers.

**Comment by mebrett** [comment]
I tried including items which either had no mapping data or no numeric data. Items without numeric data are excluded from the timeline display; items without a map show up in the timeline but it simply zooms out to the biggest view when you click to it.

**Comment by jimsafley** [comment]
For now I think everything here is within acceptable tolerances. After we get more feedback from stakeholders I'm going to merge the timeline branch into master and then come back to these specific concerns on the master branch if they become problems.
