### ISSUE TITLE
Look over timeline layout and styles

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Mapping#53]
Test with our supported themes, latest core, and master branch of the module that:

* the timeline now sits left of the map in a horizontal layout
* the timeline text uses the theme's font selections

**Comment by mebrett** [comment]
Timeline is consistently to the left of the map, and the text uses fonts from the theme. 
The left-positioning sticks on mobile view, fwiw. 
![IMG_A8ADE0ED6FF8-1](https://user-images.githubusercontent.com/2314070/66327986-c5877380-e8f9-11e9-8f7b-4ab96172abab.jpeg)

**Comment by kimisgold** [comment]
@mebrett Can you pull this latest change to see if it broke anything? The horizontal layout is awkward on mobile widths, so for those I now have the timeline in a single column layout with the map.

**Comment by mebrett** [comment]
On master branch or the timeline branch?

**Comment by kimisgold** [comment]
I pushed it to master since I think Jim's already merged the timeline branch.

**Comment by mebrett** [comment]
The timeline flags are no longer clickable (but I now can't remember if they were previously)

**Comment by kimisgold** [comment]
@mebrett You should be able to click on markers again in the latest commit on master.

**Comment by mebrett** [comment]
@kimisgold it's working now. Things look good on desktop and mobile. There's still a bit of extra room on the right in Center Row in mobile, but everything's fine on the other three themes.

**Comment by kimisgold** [comment]
Cool, I'm pretty sure the Center Row horizontal scrolling is a theme issue and Mapping is not at fault.
