### ISSUE TITLE
Timeline position controlling appearance of the pins on the map

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/Mapping#55]
Currently, the forward and backward arrows in the item pane control the appearance of the pins on the map. Can we shift that control to the timeline so that if the timeline is in a particular spot it shows all of the items that are located within that time period, not just the one that is active in the item pane?

**Comment by jimsafley** [comment]
My sense is that many users will not want this to be the default behavior—they will only want to see the markers of the _current_ event, not every marker of every event that share the same time period.

Even so, given how TimelineJS organizes events, this feature will be difficult to implement. Individual events are completely unaware of other events, so making the comparisons needed to select contemporaneous events is not at all trivial.

**Comment by sharonmleon** [comment]
I realize that this might be the primary users' desire, but it is the desire of the client who is paying for the module.

Am I understanding correctly that the interval of the date has nothing to do with the way that the pins appear on the map? The request is that the pin remain visible for the entire interval. I'm not sure that that requires the items to be aware of one another.

**Comment by sharonmleon** [comment]
Also, I imagine that this would only make sense for a user who has selected the "don't fly" mode in the map view.

**Comment by jimsafley** [comment]
I mention that this might not the primary users' desire only to indicate that such an option should be a configurable, not because I'm trying to cause friction against the wishes of a paying client.

Yes, the interval of the date has nothing to do with the way that the pins appear on the map. TimelineJS paginates from one event to another, not from one time period to another.

**Comment by sharonmleon** [comment]
And my suggestion that the feature is a connection to the contract was more to suggest that it might be better to be a fork/one-off fix?

**Comment by jimsafley** [comment]
I'm currently working on this. I stand behind my initial assessment that this will be difficult to implement, but if we are to make it work for one user, we should make it work for all, especially given that making it configurable is the only thing we need to generalize the feature.

**Comment by jimsafley** [comment]
I've implemented the feature on the [show-contemporaneous branch](https://github.com/omeka-s-modules/Mapping/tree/show-contemporaneous). I need to think on it a bit (and perhaps make some changes) before I make a testing issue.
