### ISSUE TITLE
Testing: show contemporaneous events

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#57]
The [show-contemporaneous](https://github.com/omeka-s-modules/Mapping/tree/show-contemporaneous) branch introduces a timeline configuration that toggles whether to show all events (i.e. items) on the map that exist in the same time period as the current event.

For **timestamp** properties, all events that have the same timestamp as the event in the story slider should display on the map. So if two events have a timestamp of "1886-01-01," both events should show on the map when either is in the story slider.

For **interval** properties, all events that fall in the same time period as the event in the story slider should display on the map. So if one event has an interval of "1886-01-01/1900-01-01" and another has an interval of "1898-01-01/1905-01-01," both events should show on the map when either is in the story slider.

(See #55)

**Comment by mebrett** [comment]
Interval is working as expected. (Note to self - if people are going to use this, they will need/want to label their markers, so you can tell which is which. Will need to state that in the documentation)

**Comment by mebrett** [comment]
It does work for timestamp - I had to completely delete the existing map+timeline I had with timestamp, and create a new one with the same items in order to get it to work.

**Comment by mebrett** [comment]
Styling note that it would be helpful to be able to collapse the description for this function, as it takes up a lot of screen real estate 
![Screen Shot 2019-12-17 at 11 35 52 AM](https://user-images.githubusercontent.com/2314070/71017071-0d7a0200-20c4-11ea-8646-f1c2453a390d.png)

**Comment by jimsafley** [comment]
You had to delete the map/timeline block? That's troubling. How did it break the old map/timeline?

**Comment by mebrett** [comment]
First, I made a new event at the exact same date as an event I already had in the system (prior to pulling the branch). Then I added that event to the map/timeline block. Regardless of whether I checked the "show contemp" or not, it never showed both events on the map at the same time. I tried deleting just those two events and re-adding them, but they still displayed separately.

**Comment by jimsafley** [comment]
I'm pretty sure that was a caching issue. I just reproduced the bug, did a hard refresh, and it's working now.

**Comment by mebrett** [comment]
I tried a hard refresh, but caching makes sense too

**Comment by sharonmleon** [comment]
So, I updated the module. Then I went and created two items, added them to the map and switched the timeline from interval to timestamp. They did appear simultaneously, as did the other items I already had with the same timestamps.

**Comment by jimsafley** [comment]
@sharonmleon Does this satisfy the behavior you wanted in #55? I'm still a little concerned about the bug that @mebrett saw, but I can't reproduce it anymore and it seems to have worked for you. Ideally we'd have more people testing this, but I could just merge now.

**Comment by sharonmleon** [comment]
Yes, as far as I understand the feature request, this does it. I did clear my cache before testing and I had no issues, so I think we can merge it.
