### ISSUE TITLE
Testing: full-width timeline navigation

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#58]
The [full-width-timeline](https://github.com/omeka-s-modules/Mapping/tree/full-width-timeline) branch introduces a timeline configuration that controls the layout of the timeline navigation. Users can select from three layouts:

- "Default view" (the timenav is in the default position under the story slider)
- "Full width, below story slider and map"
- "Full width, above story slider and map"

We need to test whether the timeline/map interface works as expected in each of these layouts, probably testing in each of our themes.

(See #54)

**Comment by mebrett** [comment]
Options apply as expected, and display works across all four official themes.

The map/text area scales when the timeline is above or below, but sometimes it gets very large, to the point where it's four or five times the height of the timeline. It's not a problem, per se, just an oddity in display. 
![Screen Shot 2019-12-17 at 11 21 40 AM](https://user-images.githubusercontent.com/2314070/71014279-b2dea700-20bf-11ea-8374-4ffbca60a58f.png)

**Comment by jimsafley** [comment]
@kimisgold Could the scaling that @mebrett mentions above be a product of the new styles?

**Comment by kimisgold** [comment]
Yes, I used 60vh as the default for the text and map area—I figured that giving those two areas more room would be desirable, but I can see how it could look a little odd. The timeline is fixed at 165px from the plugin itself, and its styles are involved to the point where I thought I'd leave that be.

**Comment by jimsafley** [comment]
Do you think we can reasonably convince users that this is, as @mebrett says, not a problem, per se, but an oddity in display? If so then I think we can merge.
