### ISSUE TITLE
CSV importing giving ORMInvalidArgumentException

### ISSUE THREAD

**Issue by patrickmj** [omeka-s-modules/Mapping#6]
Oddly, markers are imported okay, and bonus oddly, even when there's no csv mapping to marker data, it still appears.

2016-04-27T20:27:13+00:00 ERR (3): exception 'Doctrine\ORM\ORMInvalidArgumentException' with message 'A new entity was found through the relationship 'Mapping\Entity\Mapping#item' that was not configured to cascade persist operations for entity: Omeka\Entity\Item@000000007c1a4c5900000000179f2806. To solve this issue: Either explicitly call EntityManager#persist() on this unknown entity or configure cascade persist  this association in the mapping for example @ManyToOne(..,cascade={"persist"}). If you cannot find out which entity causes the problem implement 'Omeka\Entity\Item#__toString()' to get a clue.' in /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/ORMInvalidArgumentException.php:92
Stack trace:
#0 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(856): Doctrine\ORM\ORMInvalidArgumentException::newEntityFoundThroughRelationship(Array, Object(Omeka\Entity\Item))
#1 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(741): Doctrine\ORM\UnitOfWork->computeAssociationChanges(Array, Object(Omeka\Entity\Item))
#2 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(803): Doctrine\ORM\UnitOfWork->computeChangeSet(Object(Doctrine\ORM\Mapping\ClassMetadata), Object(Mapping\Entity\Mapping))
#3 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(340): Doctrine\ORM\UnitOfWork->computeChangeSets()
#4 /var/www/omekas/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(356): Doctrine\ORM\UnitOfWork->commit(NULL)
#5 /var/www/omekas/application/src/Api/Adapter/AbstractEntityAdapter.php(303): Doctrine\ORM\EntityManager->flush()
#6 /var/www/omekas/application/src/Api/Manager.php(341): Omeka\Api\Adapter\AbstractEntityAdapter->batchCreate(Object(Omeka\Api\Request))
#7 /var/www/omekas/application/src/Api/Manager.php(215): Omeka\Api\Manager->executeBatchCreate(Object(Omeka\Api\Request), Object(CSVImport\Api\Adapter\EntityAdapter))
#8 /var/www/omekas/application/src/Api/Manager.php(92): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#9 /var/www/omekas/modules/CSVImport/src/Job/Import.php(88): Omeka\Api\Manager->batchCreate('csvimport_entit...', Array, Array, true)
#10 /var/www/omekas/modules/CSVImport/src/Job/Import.php(63): CSVImport\Job\Import->createEntities(Array)
#11 /var/www/omekas/application/src/Job/Strategy/SynchronousStrategy.php(37): CSVImport\Job\Import->perform()
#12 /var/www/omekas/application/src/Job/Dispatcher.php(105): Omeka\Job\Strategy\SynchronousStrategy->send(Object(Omeka\Entity\Job))
#13 /var/www/omekas/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\Strategy\SynchronousStrategy))
#14 {main}

**Comment by zerocrates** [comment]
You get this error when one persisted entity (in this case, the Mapping) references another entity that isn't persisted.

The Item should be getting persisted by the batch_create call, so there's something odd happening here... are you back to continuning after error? That would explain it: an error happens, the Item never gets persisted, but the associated Mapping remains and mucks things up once we go to flush.

**Comment by patrickmj** [comment]
Same result regardless of continuing after error setting

**Comment by patrickmj** [comment]
More details:

Confirm that Item, Mapping, and MappingMarker all created, and map shows up with the marker for the item.

Maybe a matter of order? Mapping gets persisted and complains that the Item hasn't been persisted in the ErrorStore, then the Item gets persisted after all, so everything looks good on the other side?

Not sure of the sequence from the events system, but both Mappings and MappingMarkers are handled on the `'api.hydrate.post'` event on the ItemAdapter. Could that be it?

**Comment by zerocrates** [comment]
Is there no possibility that this error is for another item than the one where everything's being created correctly? With an exception like that, nothing should be getting saved.

**Comment by patrickmj** [comment]
yep. only one row to import.

**Comment by patrickmj** [comment]
seems to only happen with batchCreate

**Comment by zerocrates** [comment]
The error is actually happening when CSV Import tries to save its records of what items were inserted (and that's why the items themselves are all coming in fine: this error happens after they've already been saved).

**Comment by zerocrates** [comment]
So, the error happens because we explicitly detact entities that were created in a batch create, and just return references. The main entity, the Item, is detached, but the Mapping and/or Markers aren't, so they're still in the entity manager, and next time we flush, we see this error.

Normally you fix this by setting cascade detach on the association, but that association needs to be set on the Item, which doesn't know about the Mapping. Probably the most promising looking solution is to add that association to the Item entity at runtime using the LoadClassMetadata lifecycle event. This might not actually work because there's no underlying property and Doctrine may complain about that.

Otherwise the next best thing would be a lifecycle event for detach... but there doesn't seem to be an event for that. So, the last resort would be using the flush event, and detaching mappings that link to non-persistent Items then, just before the flush actually occurs.

**Comment by patrickmj** [comment]
@jimsafley @zerocrates Getting same thing again, but with 'Mapping\Entity\MappingMarker#item' instead of 'Mapping\Entity\Mapping#item' Not sure what's the best way to duplicate the fix
