### ISSUE TITLE
Add Item set and Item labels in the map

### ISSUE THREAD

**Issue by rafaeluriarte** [omeka-s-modules/Mapping#60]
1 - Being able to select multiple items to add as attachment is nice but when you have too many items, it might take to long, as in my case (selecting 500, one by one). It would be great to be able to attach an item set or the results of a search ("Add All").

2 - The map shows only "View Item" link, without label or image. It would great to be able to set a default property as label and a default image to be be shown in the map (e.g., the thumbnail of the item).

![Screenshot from 2020-01-27 15-04-18](https://user-images.githubusercontent.com/19567189/73180781-4ae79b80-4116-11ea-9282-4fca4ec62d0b.png)

**Comment by jimsafley** [comment]
1. An "Add all" feature is a good idea, but it wouldn't be specific to this module and will likely require a significant change to the way items are attached to blocks. I've [opened an issue](https://github.com/omeka/omeka-s/issues/1544) over on the omeka-s repository.

2. You need to set a marker label and marker image when editing your items.

**Comment by rafaeluriarte** [comment]
Thank you very much. About number  2, do I need to edit one by one? Isn't there a way to use thumbnail of the item and title?

**Comment by kalbers** [comment]
Rather than attaching, we could utilize a query the way the current Browse block works, tying the results to the map. This would be in a different map block.

**Comment by rafaeluriarte** [comment]
Sorry but for insisting but about question 2,  isn't there a way to show thumbnail of the item and its title instead  only "view item" (as in the screenshot)?

(Just found the answer - for now we can only edit Mapping/view/common/block-layout/mapping-block.phtml )
