### ISSUE TITLE
Cannot close location search input once opened

### ISSUE THREAD

**Issue by kimisgold** [omeka-s-modules/Mapping#61]
Clicking on the location search's 'x' button does nothing once the input has been opened. I've also noticed that when using Mapping within the Collecting module in the public views, markers get placed underneath wherever I click on the open location search input.

**Comment by jimsafley** [comment]
The magnifying glass closes the input. The "X" removes any text in the input.

**Comment by kimisgold** [comment]
Ah, shows how long it's been since I used Mapping. Are you at least able to see the issue with the marker showing up behind the open input on public views?

**Comment by zerocrates** [comment]
Yes, I mentioned that same problem in the Collecting-side issue. And if I dig around a little, I'm fairly certain someone has reported it in some other channel as well.

**Comment by kimisgold** [comment]
Sorry for the duplicate!
