### ISSUE TITLE
Poorly formatted Map prompt

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#62]
When rendering a collecting form with a Map prompt, the map's geosearch search bar is poorly styled. It should also be closed by default.
![Welcome · My Site · Omeka S2](https://user-images.githubusercontent.com/141955/79155521-3e7ef080-7d9f-11ea-81d9-b2f9ccd313f4.png)

**Comment by zerocrates** [comment]
The forum report on the collecting-mapping "marker under the search input" problem is https://forum.omeka.org/t/mapping-marker-location-placement-in-collecting-prompt/10438

**Comment by zerocrates** [comment]
So, do we _want_ to restore the default behavior of the geosearch bar (closed by default)? It was set to be default-open on purpose; changing it to not do that is simple.

The problem with clicks going "through" the bar, must just be that geosearch doesn't make its container consume click events. A `stopPropagation` on click events for the geosearch control should prevent them from also being seen as "map clicks."

**Comment by jimsafley** [comment]
I'm going to keep the geosearch bar open by default.

**Comment by jimsafley** [comment]
Apparently, triggering the `click` event on the geosearch bar causes the page to focus on the map when it initially loads. This is definitely buggy behavior, so I'm just going to keep the bar closed by default.
