### ISSUE TITLE
Testing: Confirm that JS updates didn't break the maps

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#63]
The [js-update branch](https://github.com/omeka-s-modules/Mapping/tree/js-update) updates key scripts that power the various maps that this module provides. Test every map on the admin and public interfaces. There should be no change to their behavior.

**Comment by mebrett** [comment]
which branch of core - develop? or master?

**Comment by jimsafley** [comment]
The current 2.x version, so master, I think.

**Comment by zerocrates** [comment]
it would be master, yeah. or release-2.1.

**Comment by mebrett** [comment]
The location search bar isn't doing anything - I can put an address in and it just sits there.

**Comment by jimsafley** [comment]
I can't reproduce. Try emptying the cache and hard reloading. Do you see any errors in the debugging console?

**Comment by mebrett** [comment]
Ah - apparently it's an issue with Open Street Map (distinct lack of robust addresses for rural North Carolina)
