### ISSUE TITLE
Testing: New Mapping block

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#66]
The [map-query](https://github.com/omeka-s-modules/Mapping/tree/map-query) block introduces the new "Map by query" site block. It's identical to the existing map block (now named "Map by attachments") except that items are attached to the map via a user-defined query - similar to the "Query" input in the "Browse preview" block. Make sure both map blocks work as expected, and that the new map block does in fact attach the results of the query.

**Comment by mebrett** [comment]
Testing against master of core?

**Comment by jimsafley** [comment]
Yes, test against the master branch.

**Comment by mebrett** [comment]
Double checked that having non-mapped items in the search results doesn't break the map (it doesn't). 

If searching by item set, the map only displays items which are are also in the site's resource pool. If an item is part of the search results but not the item pool, then the item is not displayed.

**Comment by jimsafley** [comment]
> If searching by item set, the map only displays items which are are also in the site's resource pool. If an item is part of the search results but not the item pool, then the item is not displayed.

That's not supposed to happen. Something must be applying the site filter. Are you sure your query doesn't contain `site_id=`?

**Comment by mebrett** [comment]
The query, as copied from the advanced search results on the admin site, looks like this: `?fulltext_search=&property%5B0%5D%5Bjoiner%5D=and&property%5B0%5D%5Bproperty%5D=&property%5B0%5D%5Btype%5D=eq&property%5B0%5D%5Btext%5D=&resource_class_id%5B%5D=&resource_template_id%5B%5D=&item_set_id%5B%5D=48&site_id=&submit=Search`

**Comment by mebrett** [comment]
It's working as you say, now. I'm not sure why the non-resource items weren't displaying before (I haven't changed anything with the item). 
If/when we implement, we should make it clear that it will include anything that matches the terms, regardless of site-resource limits.

**Comment by jimsafley** [comment]
Your concerns are well founded. I've made it so only items that are assigned to the current site will be displayed in the map. This brings it into line with the behavior of the "Browse preview" block.

**Comment by sharonmleon** [comment]
In testing this block, I've lost the image to set the map default view. I had the Map by attachment block above it. Once I deleted and reloaded, the default setting for this one returned. So, there might be a hint of an overload when both are in use?

**Comment by jimsafley** [comment]
I can't reproduce this. I added a "Map by attachment" block then a "Map by query" block and both default view maps render as usual. Has this happened to you since? If you can't reproduce it I suspect that either OSM had a momentary loss of service or your cache needed to refresh.

**Comment by sharonmleon** [comment]
It happened a couple of times that day, but I can't reproduce it today.

**Comment by sharonmleon** [comment]
Reopened, since I wasn't sure if Megan was done.
