### ISSUE TITLE
Testing: Configurable default basemap provider

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#69]
The [default-basemap-provider](https://github.com/omeka-s-modules/Mapping/tree/default-basemap-provider) branch introduces configurable default basemap provider for Mapping's page blocks and custom link. 

In site Pages, the "Map by attachments" and "Map by query" blocks should now have a "Basemap provider" select menu under "Default View". By selecting one, you are choosing the provider that Leaflet uses when rendering the map block. The block form's map should refresh to the new provider when selected. After saving the form, the public map block should render with the selected provider by default.

In site Navigation, the "Map Browse" custom link should now have a "Basemap provider" select menu. By selecting one, you are choosing the provider that Leaflet uses when rendering the map browse page. After saving the form, the public map browse page should render with the selected provider by default.

**Comment by mebrett** [comment]
Does it matter which branch of Omeka S?

**Comment by jimsafley** [comment]
It should work on the master branch.

**Comment by mebrett** [comment]
Need to remember in the documentation to note that some basemaps don't work at deep zoom, so to check before going public. 

For the Map Browse from Navigation, it tries to open something when I click the edit button, but I don't see any options.

**Comment by jimsafley** [comment]
Thanks for catching that. It should be fixed now. I've also added a "[Default provider]" option to the Mapping blocks and nav page configurations. They should render to the OpenStreetMap.Mapnik provider.

**Comment by mebrett** [comment]
I see it now, and it works.
Is the Map Browse page meant to have search options under the map? (I've never used it before)

**Comment by jimsafley** [comment]
Yes, it's pretty much a browse page like any other, except the advanced search is on the same page.

**Comment by mebrett** [comment]
Thanks. I'd say this is good to go.
