### ISSUE TITLE
Inherit styles from the theme

### ISSUE THREAD

**Issue by sharonmleon** [omeka-s-modules/Mapping#70]
@kimisgold My impression is that the mapping module blocks should inherit the styles from the theme, but my current test is not pulling link colors or accents in the timeline view.

http://6floors.org/teaching/black-reconstruction-legislators/s/black-reconstruction-officeholders/page/welcome

**Comment by kimisgold** [comment]
Could you point to a particular area where the styles aren't pulling in link colors or accents? I'm seeing fonts and and link colors in the timeline within this screenshot.

![Screen Shot 2020-05-15 at 2 07 03 PM](https://user-images.githubusercontent.com/606764/82082243-a766ca80-96b5-11ea-895e-271a70cee8a0.png)

The module has some of its own styles, so if anything isn't being picked up from the theme, it means the module has more specific styles overriding the theme's.

**Comment by sharonmleon** [comment]
Maybe it's my monitor? But that Title link on the left side is kind of an orange-red, and the roll-over is very dark. On the main theme the roll-over is an underline accent, but no color change. Is it possible that it's just about the weight of that header link, and again, my aging eyes?
