### ISSUE TITLE
Testing: Configurable min/max zoom levels for Mapping blocks

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#72]
The [config-map-block-zoom](https://github.com/omeka-s-modules/Mapping/tree/config-map-block-zoom) branch introduces configurable minimum zoom level and maximum zoom level for Mapping blocks (by attachment and by query). Once set, the public map's zoom limits should be constrained by the configured limits.

**Comment by mebrett** [comment]
Master of core?

**Comment by jimsafley** [comment]
Master

**Comment by mebrett** [comment]
It works as expected - sometimes takes a little doing to find the right numbers.

It did allow me to set the min zoom at a smaller number than max zoom (15 and 10). It seemed to just apply the 15 and ignore the 10

**Comment by jimsafley** [comment]
I added the current zoom level to the map block form, which should provide enough context to make good decisions when setting the minimum and maximum zoom levels. Given this addition I don't think it's worth the trouble to prevent the user from making bad decisions. What do you think?

**Comment by mebrett** [comment]
I see that and it updates as I zoom in or out. 
I agree that we don't need to prevent bad decisions, especially since it doesn't seem to break the module.
