### ISSUE TITLE
Map Browse not filtering item sets

### ISSUE THREAD

**Issue by GitByrd** [omeka-s-modules/Mapping#76]
I am just noticing that when I select an item set on the map browse page and search, it will not filter out the appropriate items, and instead include items from other item sets and sites. I have the site settings set to only show attached items and have set the item sets in its resources. Is there a way to make the map only show particular item sets, especially for its own site?

**Comment by jimsafley** [comment]
Thanks for reporting this bug. I believe it's now fixed in 6fe0cc2dce7fc64d4706615b7f03e32950f54d15. It'll be available in the next release.
