### ISSUE TITLE
Radius search throws Doctrine error

### ISSUE THREAD

**Issue by alexdryden** [omeka-s-modules/Mapping#82]
Described in the forums [here](https://forum.omeka.org/t/search-by-geographic-address-in-mapping-module-throws-error/12280), when using the search feature at `<domain>/s/<site_name>/map-browse`, Doctrine returns a semantic error:
```
Doctrine\ORM\Query\QueryException
[Semantical Error] line 0, col 148 near 'distance <= ': Error: 'distance' is not defined.
```
The alias `distance` is created [here](https://github.com/omeka-s-modules/Mapping/blob/26ebbfe1a2267f2ac26c98e6626bde8189f30a0e/src/Api/Adapter/MappingMarkerAdapter.php#L134-L145). To me it looks like the `HAVING` clause is being evaluated before the`SELECT`, so `distance` is not yet defined when the `HAVING` clause references it, causing the "not defined" error. This type of error does not reproduce when generating the query directly in MySQL. According to the MySQL [docs](https://dev.mysql.com/doc/refman/8.0/en/select.html) this is may be because:

> The SQL standard requires that HAVING must reference only columns in the GROUP BY clause or columns used in aggregate functions. However, MySQL supports an extension to this behavior, and permits HAVING to refer to columns in the SELECT list and columns in outer subqueries as well. 

My guess would be that Doctrine is enforcing the SQL standard without regard to the MySQL extension. The `HAVING` statement was added in 2bd41b035f91cd072eb543cb5202a50e784024c1. The commit's comment says, 

> Use SELECT and HAVING to filter markers by distance
Instead of WHERE. This is possible due to the recent addition of Doctrine's paginator in the search operation. Makes "ORDER BY distance" queries possible, but isn't implemented yet.

I can't find anything in the Doctrine docs that clearly references the implementation suggested there. I was able to get this to work by calculating the distance inside a `WHERE` clause. I can submit that as a pull request, or maybe @jimsafley can point me to the `HAVING` implementation they had in mind.

**Comment by jimsafley** [comment]
This is due to an optimization change in Omeka that strips all columns from the SELECT clause when calculating the total count.

Thank you for troubleshooting this issue. We will definitely appreciate a pull request.

**Comment by alexdryden** [comment]
Ah, that makes sense. @jimsafley would you mind pointing me to the release where those optimizations where introduced?

**Comment by jimsafley** [comment]
It's here https://github.com/omeka/omeka-s/commit/5cded839b2af4f20cdbc36a95d5b4063587fd717. In particular the `$countQb->select('1');`

**Comment by alexdryden** [comment]
Thanks!
