### ISSUE TITLE
Allow a large number of items to be displayed on the map

### ISSUE THREAD

**Issue by gtnbssn** [omeka-s-modules/Mapping#86]
We stumbled on this issue where our map is not showing all of the items saved in Omeka S. Others have reported it on the forum: https://forum.omeka.org/t/mapping-module-restricted-number-of-items-on-the-map/11007

Is this still being worked on?

I'm not exactly a great php coder, but i'd be happy to look into it if i can make sense out of it!

**Comment by jimsafley** [comment]
Have you tried using the "Map by Query" block? If you're having the same problem described by the forum post, using that block instead of the "Map by Attachment" block should work.

**Comment by gtnbssn** [comment]
Thanks, i think this will work for us! I'll close this issue.
