### ISSUE TITLE
Storing and showing LineStrings (for streets)

### ISSUE THREAD

**Issue by coret** [omeka-s-modules/Mapping#87]
I want to store and show street geometries on a map.

I assume asWKT is the right property for this? 
I have installed the [Data Type Geometry](https://gitlab.com/Daniel-KM/Omeka-S-module-DataTypeGeometry) so I can declare the type as Geometry.
An [example value](https://www.goudatijdmachine.nl/data/referentie/document/ark:/60537/bhh5aK) being `LINESTRING (4.7094252705574 52.0085784956308,4.70989197492599 52.0088261473882,4.71058666706085 52.0092223873495)`

But how to show the line on a map when viewing the [item](https://www.goudatijdmachine.nl/data/referentie/document/ark:/60537/bhh5aK)?

**Comment by jimsafley** [comment]
The Mapping module does not support LineStrings. Perhaps you are referencing a 3rd-party module?
