### ISSUE TITLE
CSV import default map view attributes have no effect

### ISSUE THREAD

**Issue by grandgeorg** [omeka-s-modules/Mapping#89]
When importing via CSV the default map view attributes (default zoom, map center longitude, map center latitude) have no effect at all. In fact nothing from these settings gets imported to the database. It does not matter if resource location (lat & lng) is set or not for the import.

**Comment by jimsafley** [comment]
Thanks for bringing this to our attention. It's an artifact of an old version of Mapping. Now, instead of setting a default zoom, latitude, and longitude, Mapping sets default bounds (i.e. a bounding box). The fix should be in the next release.
