### ISSUE TITLE
Testing: User-entered marker label on Collecting form

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#91]
Commit 39616f4cd03f78de1c2d5e8b27e2e24a93f7ff05 introduces the ability to label markers on maps in collecting forms. To test this you'll need to have the Collecting module installed, add an "Item media" > "Map" prompt, and add the form to a page. Go to the form on the public site and you should see an "Enter a marker label" input under the map. Enter a label and submit the form. View the new item on the admin side. The Mapping marker should be labeled accordingly.

Also, add an "Item property" > "Dublin Core: Title" prompt, placing it before (above) the map prompt. Go to the public form and enter a title but *do not* enter a marker label. The new item's marker label should be the title you entered.

**Comment by katknow** [comment]
This seems to work as described. The one concern I have (which may just be cleared up with documentation) is that if people make the map a required field if they'll think they're making the marker label required, not just the pin itself.

**Comment by sharonmleon** [comment]
I'm not convinced that this documentation actually belongs in the Mapping page; I think it might need to go in Collecting. Or something in both spots? 

We should consult with @allanaaa
