### ISSUE TITLE
Documentation: User-entered marker label on Collecting form

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#92]
See #91

**Comment by katknow** [comment]
I wasn't sure exactly where this should go, so I just added to the end of the "Adding locations to an item" section in the Mapping documentation. [You can view the draft here.](https://github.com/katknow/Drafts/blob/b49c5bb65f82f9e6aa19dd7a65c74a1c0c00df46/mapping-usermarkerlabel.md) I'm happy to make any changes, and when it's good to go I'll push it to the end user repo.

**Comment by jimsafley** [comment]
Looks good to me!

**Comment by sharonmleon** [comment]
Let's not close this until we get it into place in the docs.

**Comment by sharonmleon** [comment]
I'm not convinced that this documentation actually belongs in the Mapping page; I think it might need to go in Collecting. Or something in both spots? 

We should consult with @allanaaa

**Comment by allanaaa** [comment]
Yes, I would put this material on the Collecting page, and put a quick mention of "Integration with Collecting module" on the Mapping page that points people there for more information. 

I can take it from here if you'd like?

**Comment by katknow** [comment]
@allanaaa I'm happy to do it--are you thinking it would just become one of the bulleted lists under the "Prompts" heading?

**Comment by allanaaa** [comment]
There's already a mention there that you can expand. I'd follow the formatting of the paragraph above this, where it mentions other module integrations: 

> Item Media allows visitors to add media to their submission.
> Media Type:
> 
>     A dropdown for Media type, with the following options:
>         Upload one, which allows users to upload one file
>         Upload multiple, which allows users to upload multiple files at once using the browser's native file picker (with shift or control keys)
>         Map (requires Mapping module)
>         URL
>         HTML.
>     Prompt Text: If you want the prompt to be something other than the property label.
>     Check the "Required?" box if the prompt is required.

I'd include your second screenshot; I think it's useful to see what the addition looks like for users. 

And I would add it to the intro of the Collecting page here:

> Collecting integrates with the [Custom Vocab](https://omeka.org/s/docs/user-manual/modules/customvocab/) and the [Numeric Data Types](https://omeka.org/s/docs/user-manual/modules/numericdatatypes/) modules.

**Comment by katknow** [comment]
Okay, I added a new branch to documentation with changes to the [Collecting](https://github.com/omeka/omeka-s-enduser/blob/collecting-mapping/docs/modules/collecting.md) and [Mapping](https://github.com/omeka/omeka-s-enduser/blob/collecting-mapping/docs/modules/mapping.md) pages. Collecting I did as described above, and then Mapping I just added a line at the end of the "Adding locations to an item" section mentioning the integration with Collecting. Happy to make changes as needed!

**Comment by allanaaa** [comment]
Looks good to me. I've noticed a few other things to correct on these pages during this discussion, so after you commit this I might go in and, e.g., try to find a better spot for the image maybe. But I'm happy with it for now!
