### ISSUE TITLE
Support for geometries other than point?

### ISSUE THREAD

**Issue by majdal** [omeka-s-modules/Mapping#93]
Thanks for the very useful module! 

The module as it currently stands only supports point geometries. I think that adding other geometries, especially ones that are supported by the geojson standard, would be super useful, especially LineString and Polygon. 

Is this one the roadmap? I wish I could contribute myself, by my PHP capabilities are dismal!

**Comment by jimsafley** [comment]
There has been interest in adding additional geometries, so it is on our radar. There are some complications on how to implement them in the current state of the module, given it was developed with only points in mind, but we do plan on exploring the possibility in the future.

**Comment by m-art-in** [comment]
Any progress here? 
I am trying to reconstruct a historical itinerary and for this purpose lines would be very helpful

**Comment by jimsafley** [comment]
I've given it a great deal of thought, but there is no progress. It's not that vector layers (polylines, polygons, rectangles, and circles) are especially difficult to implement. The complication is building them into a system fundamentally designed for single geographical points.

For every feature that assumes one point per layer, we need to find a way to reconcile the addition of layers comprised of multiple points. There is no simple solution to integrating vector layers into features such as search by geographic location, batch copy coordinates, map browse page, map timeline block, module integrations (CSV Import, Collecting), etc. And it's not only a UI problem. Data format, storage, and retrieval are perhaps the trickiest aspect to this

**Comment by jimsafley** [comment]
Fixed in 36776e55e2e98c08cfca5f41e5cc4647cbab311f
