### ISSUE TITLE
Documentation: New behavior for CSV Import integration

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#97]
The [CSV Import integration](https://omeka.org/s/docs/user-manual/modules/mapping/#csv-import-integration) section needs updating to reflect a change in how users map a column to the default view. I've removed the "Default map view" dropdown and  added "Default Bounds (sw_lng,sw_lat,ne_lng,ne_lat)" to the renamed "Mapping" dropdown.

- **sw_lng**: south-west longitude
- **sw_lat**: south-west latitude
- **ne_lng**: north-east longitude
- **ne_lat**: north-east latitude

**Comment by jimsafley** [comment]
Does this section belong in the CSV Import docs instead? There is a question where module integration docs belong (see [here](https://github.com/omeka-s-modules/Mapping/issues/92#issuecomment-1233287654)), and I'm ambivalent.

**Comment by allanaaa** [comment]
Oh this is exciting. Bounds for everyone!

I've done maps/csv stuff before and it can be complicated, so I might write a longer tutorial-style section about it. 

I'd put it in the CSV Import page, with a brief reference to it on the Mapping page. CSV Import also deserves more info about [data types](https://forum.omeka.org/t/rights-statements-in-a-csv-import/16014) and other module integrations. 

I may log a few issues; I know I had some module-created properties get wiped when doing updating/replacing imports, so I'll see if I can recreate that.

**Comment by allanaaa** [comment]
I've got my site set up with the CSV Import and Mapping develop modules, and they both appear to work, but the "Mapping" tab on items now isn't displaying anything. 

Because I couldn't manually add any mapping data (none in the install beforehand), I did a CSV Import to append mapping data. That appeared to work - items that didn't show a mapping tab before show it now; items that didn't come up in a "map by attachments" search before come up now. But the mapping tabs are still blank, and the map page block is also blank after adding items.

**Comment by jimsafley** [comment]
Ah, yes. I forgot to mention that you'll need to install dependencies for the Mapping module. Run `npm install` in the the module's /asset directory.

**Comment by allanaaa** [comment]
Thanks, that works. 

Do these four coordinates default in some way? Say, if the map on the page is square, and you haven't provided perfectly square coordinates, does it just contain all four points and then show whatever excess is needed? Something like that?

**Comment by allanaaa** [comment]
CSV Import Revising and Updating don't work - getting an error about a duplicate value. I'm revising/updating the lat, long, and bounds every time, but only bounds are throwing up the error I think:

> 2022-11-17T17:17:54+00:00 ERR (3): PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1465' for key 'UNIQ_49E62C8A126F525E' in /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:117
> Stack trace:
> #0 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): PDOStatement->execute(NULL)
> #1 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(179): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
> #2 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(226): Doctrine\DBAL\Statement->execute(NULL)
> #3 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(276): Doctrine\DBAL\Statement->executeStatement()
> #4 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1128): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
> #5 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(425): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
> #6 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(392): Doctrine\ORM\UnitOfWork->commit(NULL)
> #7 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(447): Doctrine\ORM\EntityManager->flush()
> #8 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
> #9 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
> #10 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(796): Omeka\Api\Manager->update('items', '1465', Array, Array, Array)
> #11 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(424): CSVImport\Job\Import->updateRevise('items', '1465', Array, 'revise')
> #12 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(296): CSVImport\Job\Import->update(Array, Array, 'revise')
> #13 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(194): CSVImport\Job\Import->processBatchData(Array)
> #14 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Job/DispatchStrategy/Synchronous.php(34): CSVImport\Job\Import->perform()
> #15 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
> #16 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/data/scripts/perform-job.php(66): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
> #17 {main}
> 
> Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1465' for key 'UNIQ_49E62C8A126F525E' in /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
> Stack trace:
> #0 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(119): Doctrine\DBAL\Driver\PDO\Exception::new(Object(PDOException))
> #1 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(179): Doctrine\DBAL\Driver\PDOStatement->execute(NULL)
> #2 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Statement.php(226): Doctrine\DBAL\Statement->execute(NULL)
> #3 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(276): Doctrine\DBAL\Statement->executeStatement()
> #4 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1128): Doctrine\ORM\Persisters\Entity\BasicEntityPersister->executeInserts()
> #5 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(425): Doctrine\ORM\UnitOfWork->executeInserts(Object(Doctrine\ORM\Mapping\ClassMetadata))
> #6 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(392): Doctrine\ORM\UnitOfWork->commit(NULL)
> #7 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(447): Doctrine\ORM\EntityManager->flush()
> #8 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
> #9 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
> #10 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(796): Omeka\Api\Manager->update('items', '1465', Array, Array, Array)
> #11 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(424): CSVImport\Job\Import->updateRevise('items', '1465', Array, 'revise')
> #12 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(296): CSVImport\Job\Import->update(Array, Array, 'revise')
> #13 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(194): CSVImport\Job\Import->processBatchData(Array)
> #14 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Job/DispatchStrategy/Synchronous.php(34): CSVImport\Job\Import->perform()
> #15 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
> #16 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/data/scripts/perform-job.php(66): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
> #17 {main}
> 
> Next Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO mapping (bounds, item_id) VALUES (?, ?)' with params ["4.253008542575894,43.95470699011109,-12.123923361479552,36.456051114505925", 1465]:
> 
> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1465' for key 'UNIQ_49E62C8A126F525E' in /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:74

**Comment by jimsafley** [comment]
> Do these four coordinates default in some way? 

Leaflet will do its best to resolve the bounding box, but the coordinates do need to make some sense, e.g. south-west and north-east can't be switched.

**Comment by jimsafley** [comment]
> CSV Import Revising and Updating don't work

What are the exact steps you took to get this error?

**Comment by allanaaa** [comment]
Start a CSV Import, looks like this:
```
o:id	Latitude	Longitude	Default map view
1465	40.7986461846851	-3.645817429	4.253008542575894,43.95470699011109,-12.123923361479552,36.456051114505925
```

Set to "Revise" or "Update" under advanced settings, map columns as needed. 

If I go manually erase the mapping data for the item in question, then do a CSV Import to append or update, it works fine. But if there's already data on the item, revising or updating the default field causes the error.

**Comment by jimsafley** [comment]
You've discovered a bug that has likely been around for a long time, just undiscovered until now. I've created an issue (#98).

**Comment by allanaaa** [comment]
1) We shouldn't require all three fields to be in every import, right? (Lat, Long, Bounds)
What I'm seeing is:

- Taking an item that has existing bounds (no markers) and CSV-appending lat/long is working, but wiping the bounds.
- Taking an item that has an existing marker (no bounds) and CSV-appending bounds is failing. (see 3)
- Taking an item that has existing bounds (no marker) and CSV-appending both is failing (constraint violation on bounds).
- Taking an item that has an existing marker (no bounds) and CSV-appending both is working, but overwriting the old marker. Even though Append shouldn't be erasing anything by definition, and an item should be able to have multiple values in this case? (see 2)
- An item without any mapping data at all will take CSV-appended bounds (no markers) just fine. 

2) Is it expected behaviour that you can't save multiple markers on an item with CSV Import? I tried to do a multiple-markers-in-one-CSV (two rows with the same item ID) as an Append and that only saved the last row's data. 

3) I'm not sure if this is the same bug you're already working on, but, appending the bounds field on its own is giving me an issue. Start with an item that has a mapping marker already but no bounds data, use CSV Import to append only a bounds column (same CSV structure as I've been using), and the process appears as "Completed" but no items are updated:

```
2022-11-21T19:55:43+00:00 ERR (3): exception 'Omeka\Api\Exception\ValidationException' in /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php:654
Errors:
{
    "o-module-mapping:lat": [
        "A marker must have a numeric latitude."
    ],
    "o-module-mapping:lng": [
        "A marker must have a numeric longitude."
    ]
}
Stack trace:
#0 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/Mapping/Module.php(402): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Mapping\Entity\MappingMarker), Object(Omeka\Stdlib\ErrorStore))
#1 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Mapping\Module->handleMarkers(Object(Laminas\EventManager\Event))
#2 /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\EventManager\Event))
#3 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(643): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\EventManager\Event))
#4 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(445): Omeka\Api\Adapter\AbstractEntityAdapter->hydrateEntity(Object(Omeka\Api\Request), Object(Omeka\Entity\Item), Object(Omeka\Stdlib\ErrorStore))
#5 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Manager.php(233): Omeka\Api\Adapter\AbstractEntityAdapter->update(Object(Omeka\Api\Request))
#6 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Manager.php(136): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#7 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(761): Omeka\Api\Manager->update('items', '1461', Array, Array, Array)
#8 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(421): CSVImport\Job\Import->append('items', '1461', Array)
#9 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(296): CSVImport\Job\Import->update(Array, Array, 'append')
#10 /var/www/html/amayer/amayer-s/amsdev/omeka-s/modules/CSVImport/src/Job/Import.php(194): CSVImport\Job\Import->processBatchData(Array)
#11 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Job/DispatchStrategy/Synchronous.php(34): CSVImport\Job\Import->perform()
#12 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#13 /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/data/scripts/perform-job.php(66): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
#14 {main}
2022-11-21T19:55:43+00:00 NOTICE (5): None of the 1 items were updated (append).
```

**Comment by allanaaa** [comment]
Oh, actually, this version of the module is throwing up that error ("A marker must have a numeric latitude") on every single row that doesn't have lat/long included, no matter what it is you're actually trying to import. So I'll wait until that's fixed and go from there.

I just realized that if we wanted multiples values in a CSV Import we would use a multivalue separator on a single cell, not multiple rows, so scratch my second point above, and replace it with:

Sending two lat/longs (in the form of "48/-99;50/-98") works fine.
Sending two lats ("48;50") and two longs ("-99;-98") throws up the same error as before ("A marker must have a numeric latitude") and nothing is saved to the item.

**Comment by allanaaa** [comment]
I tested the multivalue separators on a non-development install, and it appears to be true then too: lat;lat and long;long don't work, but lat/long;lat/long works. I can just document this instead of you changing it - up to you.

**Comment by jimsafley** [comment]
When was the last time you pulled changes? About nine days ago I made a change (a442bef9274655c125fdd7dff32ba0181041ef06) that may have resolved your first point. As for your second point, just change the documentation to match the current behavior. Your third point may be related to the bug I'm working on, but it may have been resolved with the above fix.

It's obvious that this module's CSV integration has not been thoroughly tested, or hasn't caught up with CSV Import's ongoing development. Mapping also is unique in how it hydrates and stores it's data, due to marker and bounds data being separate resources, so there is a chance that fixing this will require significant changes to its approach to hydration. In the meantime we may have to document these bugs an recommend that people don't append.

**Comment by allanaaa** [comment]
Just grabbed the latest code. Revising and updating (and appending) the bounds value still results in that error. You'd expect it on appending, so it's not appending that's the problem, it's revising and updating. 

```
Next Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO mapping (bounds, item_id) VALUES (?, ?)' with params ["-135.27,22.2,-61.2,49.4", 1461]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1461' for key 'UNIQ_49E62C8A126F525E' in /var/www/html/amayer/amayer-s/amsdev/omeka-s/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:74
```

The "A marker must have a numeric latitude" issue appears to be fixed, thanks! And I will document the multivalue separator behaviour. 
 
I'm going to do some more testing on other module interactions, but I will create CSV Import & other module issues for those.

**Comment by jimsafley** [comment]
Resolving issue #98 may resolve your first point, but it also may be related to how the module hydrates incoming data. It's a complicated issue, so I don't think we can resolve it until after the next release. Perhaps in the meantime you can mention these caveats in documentation.

**Comment by allanaaa** [comment]
My mistake, the second issue doesn't seem to be resolved - 

```
2022-11-30T19:11:53+00:00 ERR (3): exception 'Omeka\Api\Exception\ValidationException' in /var/www/html/amayer/amayer-s/amsdev/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php:654
Errors:
{
    "o-module-mapping:lat": [
        "A marker must have a numeric latitude."
    ],
    "o-module-mapping:lng": [
        "A marker must have a numeric longitude."
    ]
```

I thought I had checked it thoroughly but the same process as above caused it again:

> Start with an item that has a mapping marker already but no bounds data, use CSV Import to append only a bounds column (same CSV structure as I've been using), and the process appears as "Completed" but no items are updated

**Comment by jimsafley** [comment]
I'll have to address all this after the next release.

**Comment by allanaaa** [comment]
To be clear, ANY csv import append/revise/update process done while the Mapping module is activated will result in an error if it doesn't include a numeric latitude or longitude value for every item. (It works if you include just one of the two values.) 

Maybe someone else can try to replicate this for me? The issue might become clearer.

**Comment by jimsafley** [comment]
@allanaaa Getting back to this. Now that a fix has been made for the above bug, did the original documentation request go through?
