### ISSUE TITLE
Testing: Search by map marker presence

### ISSUE THREAD

**Issue by jimsafley** [omeka-s-modules/Mapping#99]
This module now adds a "Search by map marker presence" field to the admin and public item advanced search pages. Test this by adding map markers to some of your items and seeing whether a search for "Has map markers" and "Has no map markers" works as expected. This is on the `master` branch.

**Comment by katknow** [comment]
I've pulled and it says everything is up to date, but when I'm trying to edit maps on the admin side I'm just getting a blank white screen under the mapping tab: 

![Screenshot 2022-11-28 at 09-44-45 Edit · Elizabeth II · Items · Katie's Omeka S Testing Site](https://user-images.githubusercontent.com/84726696/204306499-e4574b57-c8a7-4a3a-86a8-430715accaae.png)

**Comment by jimsafley** [comment]
Sorry. I forgot to mention that you'll need to install dependencies for the Mapping module. Run `npm install` in the the module's /asset directory.

**Comment by katknow** [comment]
This is working as described across browsers and with a variety of combinations of fields being used in the advanced search.
